### ISSUE TITLE
Potential typo page 36

### ISSUE THREAD

**Issue by ngiann** [jmzobitz/ModelingWithR#8]
I think that in the last paragraph of section 3.1, page 36 (just above section 3.2), the current sentence

_"For Equation (3.1), this means that we are solving  dE/dt = ..."_

should read instead:

_"For Equation (3.1), this means that we are solving  **dN/dt** = ..."_

I could be wrong of course.

**Comment by jmzobitz** [comment]
Thank you so much for this!  I'll be updating this (and other small typos
I've found) in a few weeks.

In appreciation,
John
***********
John M. Zobitz, PhD
Pronouns: He, him, his

Professor of Mathematics and Data Science
Data Science Program Director
Environmental Studies Program
Augsburg University
2211 Riverside Avenue, CB 93
Minneapolis, MN 55454

Hagfors Center 187
P: (612) 330-1068

**Comment by ngiann** [comment]
You are most welcome. I am reading the book rather than the online version. Is there a better/other place to report book issues perhaps?

I will wait for your corrections before I report other little typos.

I am enjoying the book very much!

**Comment by jmzobitz** [comment]
Thanks for the feedback!  I would report them as github issues - that way I
can keep a running list.  It will be ok if you post them and I may have
addressed them already.

You also bring up a good point  - I'll also start a running document of
errata that corresponds to physical book - that way it'll be easier for
readers rather than looking through a host of github issues.

Cheers,
John

***********
John M. Zobitz, PhD
Pronouns: He, him, his

Professor of Mathematics and Data Science
Data Science Program Director
Environmental Studies Program
Augsburg University
2211 Riverside Avenue, CB 93
Minneapolis, MN 55454

Hagfors Center 187
P: (612) 330-1068

**Comment by jmzobitz** [comment]
Fixed in html version and in running google doc of textbook errata: [LINK](https://docs.google.com/document/d/1BJmyeQbrDRmUdoM11pZTA_kTV0XG76L1UQLOxCIR8M0/edit?usp=sharing)
